Feature/jwt based auth
folkehelseinstituttet/fhi.helseid pull request #22
Opened 2020-11-05 15:04 UTC by runegri

Legger til støtte for klientautentisering via signerte jwt-er. 
Støtter signering med jwk, rsa-nøkkel og virksomhetssertifikat, samt den gode gamle delte hemmeligheten som vi bruker i dag.

Denne skal være bakoverkompatibel med eksisterende løsninger siden den legger på et optional parameter i AddHelseIdWebAuthentication. 

Innfører et nytt interface, IHelseIdSecretHandler, som brukes for å koble opp riktig håndtering av hemmelighet. Inkluderer fire implementasjoner som tar seg av de forskjellige typene av hemmeligheter. 

Skulle likt å få dette til å kjøre med dependency injection, men siden det gjøres i oppstarten av applikasjonen så er dette vanskelig. Man må derfor opprette handleren selv og eventuelle avhengigheter denne skulle ha. 

For jwk og rsa-xml så antar vi nå at hemmeligheten peker til en fil som inneholder selve hemmeligheten. For virksomhetssertifikater må hemmeligheten peke til et sertifikat i en sertifikat store og skal være på formatet StoreNavn:Thumbprint. For shared secret så er hemmeligheten som før.

2020-11-05 15:04 UTC, runegri commented
Tror ikke denne merger, men kommenter på api-et i første omgang.

2020-11-09 09:24 UTC, OsirisTerje requested changes
1) Noen comments på custom exception: Siden det er flere steder, kunne det vært en type (HelseIdSecuritySetupException eller noe sånt)  som ble brukt.  
2) Kunne vi fått inn tester av denne koden også ?

2020-11-09 09:24 UTC, OsirisTerje commented on Fhi.HelseId/Identity/Jwt.cs
> +            catch (Exception ex)
Trengs denne, når den kun thrower igjen?

2020-11-09 09:24 UTC, OsirisTerje commented on Fhi.HelseId/Identity/Jwt.cs
> +                    throw new Exception(string.Format("Unsupported JSON type for claim types: {0}", unsupportedJsonClaimTypes.Aggregate((x, y) => x + ", " + y)));
Hadde vært bra med en custom exception her  UnsupportedJsonClaimTypeException

2020-11-09 09:24 UTC, OsirisTerje commented on Fhi.HelseId/Identity/Jwt.cs
> +                        throw new Exception(string.Format("Can't add two claims where one is a JSON object and the other is not a JSON object ({0})", group.Key));
Customexception hadde vært bra her også

2020-11-09 09:24 UTC, OsirisTerje commented on Fhi.HelseId/Web/Services/HelseIdSecretHandlers.cs
> +                throw new Exception("For enterprise certificates we expect secret in the format STORE:Thumbprint. For example: 'LocalMachine:1234567890'");
Custom exception :-)

2020-11-09 11:28 UTC, runegri commented on Fhi.HelseId/Identity/Jwt.cs
> +            catch (Exception ex)
Kun når man debugger og vil ha et breakpoint :-)

2020-11-09 12:14 UTC, OsirisTerje approved these changes

2020-11-09 12:15 UTC, merged